# Generated by Django 5.0.6 on 2024-08-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("specialty", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=255)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=255
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("linkedin", models.URLField(null=True)),
                ("github", models.CharField(max_length=255, null=True)),
                ("photo", models.ImageField(null=True, upload_to="team_images/")),
                ("about_me", models.TextField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
